---
title: "STAT350"
author: "Hyungtae"
date: "20/11/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## R Markdown


```{r}
real_estate<-read.csv("Real estate.csv", header=TRUE)
real_estate<-real_estate[,-1]
real_estate <- real_estate[complete.cases(real_estate),]

names(real_estate)[1]<-"transaction_date"
names(real_estate)[2]<-"house_age"
names(real_estate)[3]<-"distance_to_the_nearest_MRT_station"
names(real_estate)[4]<-"number_of_convenience_stores"
names(real_estate)[5]<-"latitude"
names(real_estate)[6]<-"longitude"
names(real_estate)[7]<-"house_price_of_unit_area"

pairs(real_estate[,2:7])

summary(real_estate)
estate.lm<-lm(house_price_of_unit_area ~ transaction_date + house_age + distance_to_the_nearest_MRT_station + number_of_convenience_stores + latitude + longitude,data=real_estate)

summary(estate.lm)

estate2.lm<-lm(house_price_of_unit_area ~ transaction_date + house_age + distance_to_the_nearest_MRT_station + number_of_convenience_stores + latitude, data=real_estate)
summary(estate2.lm)

# Unit Normal Scaling things to do
#s1<-sqrt(sum((x1-mean(x1))^2)/(n-1))
#s2<-sqrt(sum((x1-mean(x2))^2)/(n-1))
#sy<-sqrt(sum((y-mean(y))^2)/(n-1))

#z1<-(x1-mean(x1))/s1
#z2<-(x2-mean(x2))/s2
#ys<-(y-mean(y))/sy

#LifeSRModel<-lm(ys~z1+z2-1)
#LifeSRModel$coefficients

#multicollinearity
library(faraway)
vif(estate2.lm) # all of them less than 10 

resid(estate2.lm)
rstandard(estate2.lm)
rstudent(estate2.lm)
plot(estate.lm)

library(ggmap)
longitude<-real_estate$longitude
latitude<-real_estate$latitude
price<-real_estate$house_price_of_unit_area
locations<-cbind(longitude,latitude)
library(tidyverse)
locations<-as.tibble(locations)
library(sf)
library(mapview)
locations_sf<-st_as_sf(locations,coords=c("longitude","latitude"),crs=4326)


locations_price<-cbind(locations,price)
locations_price$indicator<-0
locations_price$indicator<-floor(locations_price$price/10)
locations_sf<-st_as_sf(locations_price,coords=c("longitude","latitude"),crs=4326)
mapview(locations_sf,zcol= "price", at = seq(0,120,60),legend=TRUE)

#Differentiating newtaipei and taipei
new_taipei<-c(36,229,345,284,213,337,316,26,53,206,245,261,280,329,267,305,119,368,254,399,347,37,
              61,243,409,352,370,402,63,296,354,21,366,93,84,353,388,235,389,303,395,250,348,256,
              117,233,59,177,181,332,171,49,90,385,410,330,232,195,149,383,60,293,310,230,94,331,252,56)
new_taipei_estate<-real_estate[(new_taipei),]
locations_newtaipei_price<-locations_price[(new_taipei),]
locations_sf<-st_as_sf(locations_newtaipei_price,coords=c("longitude","latitude"),crs=4326)
mapview(locations_sf)
real_estate$newtaipei<-0
real_estate[(new_taipei),8]<-1

bitan<-c(378,327,406,279,320,372,28,154,288)
west<-c(270,249,201,248,376,308,355,205,283,311,52,367,392,408,185)
real_estate$bitan<-0
real_estate[(bitan),9]<-1

real_estate$west<-0
real_estate[(west),10]<-1

estate.lm<-lm(house_price_of_unit_area ~ transaction_date + house_age + distance_to_the_nearest_MRT_station + number_of_convenience_stores + latitude + longitude + newtaipei,data=real_estate)

summary(estate.lm)

library(MASS)
step.model<- stepAIC(estate.lm,direction="both",track=FALSE)
summary(step.model)
```


